import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
} from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import axios from 'axios';

const BACKEND_URL = process.env.EXPO_PUBLIC_BACKEND_URL;

export default function AITrainingPlanScreen() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<any>(null);
  const [daysPerWeek, setDaysPerWeek] = useState(4);
  const [equipment, setEquipment] = useState<string[]>([
    'barbell',
    'dumbbell',
    'cable',
    'machine',
  ]);

  const generatePlan = async () => {
    try {
      setLoading(true);
      const userId = await AsyncStorage.getItem('userId');
      if (!userId) {
        alert('Please set up your profile first');
        return;
      }

      const response = await axios.post(
        `${BACKEND_URL}/api/training-plans/generate`,
        {
          user_id: userId,
          days_per_week: daysPerWeek,
          duration_weeks: 12,
          equipment_available: equipment,
        }
      );

      setPlan(response.data);
    } catch (error) {
      console.error('Error generating plan:', error);
      alert('Failed to generate training plan');
    } finally {
      setLoading(false);
    }
  };

  const toggleEquipment = (item: string) => {
    if (equipment.includes(item)) {
      setEquipment(equipment.filter((e) => e !== item));
    } else {
      setEquipment([...equipment, item]);
    }
  };

  if (plan) {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => setPlan(null)}>
            <MaterialCommunityIcons name="arrow-left" size={24} color="#ffffff" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Your Training Plan</Text>
          <TouchableOpacity onPress={() => router.back()}>
            <MaterialCommunityIcons name="close" size={24} color="#ffffff" />
          </TouchableOpacity>
        </View>

        <ScrollView style={styles.content}>
          <View style={styles.planHeader}>
            <MaterialCommunityIcons name="robot" size={60} color="#ff1e00" />
            <Text style={styles.planTitle}>{plan.plan_name}</Text>
            <View style={styles.planMeta}>
              <View style={styles.metaChip}>
                <MaterialCommunityIcons name="calendar" size={16} color="#ff1e00" />
                <Text style={styles.metaText}>{plan.days_per_week} days/week</Text>
              </View>
              <View style={styles.metaChip}>
                <MaterialCommunityIcons name="clock" size={16} color="#ff1e00" />
                <Text style={styles.metaText}>{plan.duration_weeks} weeks</Text>
              </View>
            </View>
          </View>

          <View style={styles.planCard}>
            <Text style={styles.planSectionTitle}>AI-GENERATED PLAN</Text>
            <Text style={styles.planText}>{plan.ai_recommendations}</Text>
          </View>

          <TouchableOpacity style={styles.startButton}>
            <Text style={styles.startButtonText}>START THIS PLAN</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.regenerateButton}
            onPress={() => {
              setPlan(null);
            }}
          >
            <MaterialCommunityIcons name="refresh" size={20} color="#ff1e00" />
            <Text style={styles.regenerateText}>Generate New Plan</Text>
          </TouchableOpacity>
        </ScrollView>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()}>
          <MaterialCommunityIcons name="arrow-left" size={24} color="#ffffff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>AI Training Plan</Text>
        <View style={{ width: 24 }} />
      </View>

      <ScrollView style={styles.content}>
        <View style={styles.intro}>
          <MaterialCommunityIcons name="robot" size={80} color="#ff1e00" />
          <Text style={styles.introTitle}>AI-Powered Training</Text>
          <Text style={styles.introSubtitle}>
            Get a personalized workout plan generated by GPT-4 based on your goals
            and experience level
          </Text>
        </View>

        {/* Days per Week */}
        <Text style={styles.label}>Training Days per Week</Text>
        <View style={styles.daysContainer}>
          {[3, 4, 5, 6].map((days) => (
            <TouchableOpacity
              key={days}
              style={[
                styles.dayButton,
                daysPerWeek === days && styles.dayButtonActive,
              ]}
              onPress={() => setDaysPerWeek(days)}
            >
              <Text style={styles.dayText}>{days}</Text>
              <Text style={styles.dayLabel}>days</Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Equipment */}
        <Text style={styles.label}>Available Equipment</Text>
        <View style={styles.equipmentContainer}>
          {[
            { value: 'barbell', label: 'Barbell', icon: 'weight' },
            { value: 'dumbbell', label: 'Dumbbell', icon: 'dumbbell' },
            { value: 'cable', label: 'Cable', icon: 'link' },
            { value: 'machine', label: 'Machine', icon: 'cog' },
            { value: 'bodyweight', label: 'Bodyweight', icon: 'human' },
          ].map((item) => (
            <TouchableOpacity
              key={item.value}
              style={[
                styles.equipmentChip,
                equipment.includes(item.value) && styles.equipmentChipActive,
              ]}
              onPress={() => toggleEquipment(item.value)}
            >
              <MaterialCommunityIcons
                name={item.icon as any}
                size={20}
                color={equipment.includes(item.value) ? '#ffffff' : '#888'}
              />
              <Text style={styles.equipmentText}>{item.label}</Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Generate Button */}
        <TouchableOpacity
          style={styles.generateButton}
          onPress={generatePlan}
          disabled={loading}
        >
          {loading ? (
            <ActivityIndicator color="#ffffff" />
          ) : (
            <>
              <MaterialCommunityIcons name="auto-fix" size={24} color="#ffffff" />
              <Text style={styles.generateButtonText}>GENERATE PLAN</Text>
            </>
          )}
        </TouchableOpacity>

        {/* Info Card */}
        <View style={styles.infoCard}>
          <MaterialCommunityIcons name="information" size={24} color="#ff1e00" />
          <Text style={styles.infoText}>
            The AI will analyze your profile and create a customized training plan
            with specific exercises, sets, reps, and progression strategies tailored
            to your goals.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    paddingTop: 50,
    backgroundColor: '#1a1a1a',
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ffffff',
  },
  content: {
    flex: 1,
    padding: 16,
  },
  intro: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  introTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#ffffff',
    marginTop: 20,
  },
  introSubtitle: {
    fontSize: 15,
    color: '#888888',
    textAlign: 'center',
    marginTop: 12,
    paddingHorizontal: 20,
    lineHeight: 22,
  },
  label: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 16,
    marginTop: 24,
  },
  daysContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  dayButton: {
    flex: 1,
    backgroundColor: '#1a1a1a',
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    gap: 4,
    borderWidth: 2,
    borderColor: '#333333',
  },
  dayButtonActive: {
    backgroundColor: '#ff1e00',
    borderColor: '#ff1e00',
  },
  dayText: {
    fontSize: 32,
    fontWeight: '800',
    color: '#ffffff',
  },
  dayLabel: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
  },
  equipmentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  equipmentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 24,
    gap: 8,
    borderWidth: 2,
    borderColor: '#333333',
  },
  equipmentChipActive: {
    backgroundColor: '#ff1e00',
    borderColor: '#ff1e00',
  },
  equipmentText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#ff1e00',
    padding: 20,
    borderRadius: 12,
    marginTop: 32,
  },
  generateButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 2,
  },
  infoCard: {
    flexDirection: 'row',
    backgroundColor: '#1a1a1a',
    padding: 20,
    borderRadius: 16,
    marginTop: 24,
    gap: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#ff1e00',
  },
  infoText: {
    flex: 1,
    fontSize: 14,
    color: '#cccccc',
    lineHeight: 20,
  },
  planHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  planTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#ffffff',
    marginTop: 16,
    textAlign: 'center',
  },
  planMeta: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  metaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#252525',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    gap: 6,
  },
  metaText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ffffff',
  },
  planCard: {
    backgroundColor: '#1a1a1a',
    padding: 20,
    borderRadius: 16,
    marginBottom: 24,
  },
  planSectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#ff1e00',
    marginBottom: 16,
    letterSpacing: 1,
  },
  planText: {
    fontSize: 15,
    color: '#cccccc',
    lineHeight: 24,
  },
  startButton: {
    backgroundColor: '#ff1e00',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  startButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 2,
  },
  regenerateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#252525',
    padding: 16,
    borderRadius: 12,
    marginBottom: 24,
  },
  regenerateText: {
    color: '#ff1e00',
    fontSize: 15,
    fontWeight: '700',
  },
});
